# -*- coding: utf-8 -*-
"""
Part 5 — extra FIXED entries for paragraphs that remain partially or fully
untranslated after the first translation pass.

Generated by comparing the source document
    section/original_new_part5.docx
with the translated document
    section_translate/opus/original_new_part5.docx

Each key is the EXACT original English paragraph text; each value is the
professional Russian aviation-technical translation.

Usage:
    from part5_fixed_entries import PART5_EXTRA_FIXED
    # merge into the main FIXED dict before translating
"""

PART5_EXTRA_FIXED = {

    # ── REPAIR heading numbers with "and" ──────────────────────────────────
    "REPAIR No. 18-3, 18-4 and 18-6":
        "РЕМОНТ № 18-3, 18-4 и 18-6",
    "REPAIR No. 18-7 and 18-8":
        "РЕМОНТ № 18-7 и 18-8",
    "REPAIR No. 21-3 and 21-6":
        "РЕМОНТ № 21-3 и 21-6",
    "REPAIR No. 21-1 and 21-4":
        "РЕМОНТ № 21-1 и 21-4",
    "REPAIR No. 21-2 and 21-5":
        "РЕМОНТ № 21-2 и 21-5",

    # ── Repair 1-1 Lower Bearing Subassembly (gland housing / liner) ──────
    "Remove all of the adhesive from the external diameter of the gland housing and the internal diameter of the liner: refer to CLEANING.":
        "Удалите весь клей с наружного диаметра корпуса сальника и внутреннего диаметра вкладыша: обратитесь к CLEANING.",

    "Measure the diameter of the gland housing across the contact area: this must be between 211,328 and 211,368 mm (8.3200 and 8.3215 in).":
        "Измерьте диаметр корпуса сальника по контактной области: он должен быть в пределах 211,328 и 211,368 мм (8.3200 и 8.3215 дюйма).",

    "Clean the contact surfaces of the liner and the gland housing: use the cleaning tissues, Material Ref. Item TBA, and the cleaning agent, Material Ref. Item 11-583.":
        "Очистите контактные поверхности вкладыша и корпуса сальника: используйте чистящие салфетки, мат. ссылка позиция TBA, и чистящее средство, мат. ссылка позиция 11-583.",

    "Apply adhesive, Material Ref. Item 08-722, to the contact surface of the liner near to the scarf joints: refer to M-DLPS724.":
        "Нанесите клей, мат. ссылка позиция 08-722, на контактную поверхность вкладыша вблизи стыков: обратитесь к M-DLPS724.",

    "Assemble the liner to the gland housing.":
        "Установите вкладыш на корпус сальника.",

    "Remove the damaged liner and remove all of the adhesive from the external diameter of the gland housing: refer to CLEANING.":
        "Удалите повреждённый вкладыш и удалите весь клей с наружного диаметра корпуса сальника: обратитесь к CLEANING.",

    "Temporarily put the repair liner in position on the gland housing. If necessary, cut the repair liner at the scarf joints to adjust its length.":
        "Временно установите ремонтный вкладыш в положение на корпус сальника. При необходимости, подрежьте ремонтный вкладыш по стыкам для регулировки длины.",

    "Alternative procedure for paragraphs (j) to (m): apply Alocrom to the contact surface of the gland housing: refer to PCS-2220, type 2.":
        "Альтернативная процедура для пунктов (j) — (m): нанесите Alocrom на контактную поверхность корпуса сальника: обратитесь к PCS-2220, тип 2.",

    "Clamp the repair liner to the gland housing using an applicable tool.":
        "Зажмите ремонтный вкладыш на корпусе сальника с помощью подходящего инструмента.",

    "Put the gland housing in the preheated oven, kept at between 35 and 45 \u00b0C (95 and 113 \u00b0F), for 345 to 375 minutes.":
        "Поместите корпус сальника в предварительно нагретую печь, поддерживаемую при температуре от 35 до 45 °C (от 95 до 113 °F), на 345–375 минут.",

    "Remove the gland housing from the oven and allow to cool for a minimum of 30 minutes.":
        "Извлеките корпус сальника из печи и дайте остыть в течение не менее 30 минут.",

    "Machine the diameter and width of the repair liner to the dimensions given in Figure 601 then remove the adhesive PVC tape, Material Ref. Item TBA.":
        "Обработайте диаметр и ширину ремонтного вкладыша до размеров, указанных на Рисунке 601, затем удалите клейкую ПВХ-ленту, мат. ссылка позиция TBA.",

    # ── Repair 1-2 Lower Bearing Subassembly ──────────────────────────────
    "Remove the used adhesive from the external diameter of the gland housing and the internal diameter of the liner: refer to CLEANING.":
        "Удалите использованный клей с наружного диаметра корпуса сальника и внутреннего диаметра вкладыша: обратитесь к CLEANING.",

    "Put the liner in position on the gland housing. If necessary, cut the liner at the scarf joints to adjust its length.":
        "Установите вкладыш в положение на корпус сальника. При необходимости, подрежьте вкладыш по стыкам для регулировки длины.",

    "Clean the surfaces of the liner and the gland housing that will touch: use the cleaning tissues, Material Ref. Item TBA and the cleaning agent, Material Ref. Item 11-583.":
        "Очистите поверхности вкладыша и корпуса сальника, которые будут контактировать: используйте чистящие салфетки, мат. ссылка позиция TBA и чистящее средство, мат. ссылка позиция 11-583.",

    "Apply adhesive, Material Ref. Item 08-722, to the cleaned surface of the liner near to the scarf joints: refer to M-DLPS724.":
        "Нанесите клей, мат. ссылка позиция 08-722, на очищенную поверхность вкладыша вблизи стыков: обратитесь к M-DLPS724.",

    "Remove the damaged liner and remove the used adhesive from the external diameter of the gland housing: refer to CLEANING.":
        "Удалите повреждённый вкладыш и удалите использованный клей с наружного диаметра корпуса сальника: обратитесь к CLEANING.",

    "Put the repair liner in position on the gland housing. If necessary, cut the repair liner at the scarf joints to adjust its length.":
        "Установите ремонтный вкладыш в положение на корпус сальника. При необходимости, подрежьте ремонтный вкладыш по стыкам для регулировки длины.",

    "Set the temperature of an oven to between 35 and 45 oC (95 and 113 oF).":
        "Установите температуру печи от 35 до 45 °C (от 95 до 113 °F).",

    "Put the gland housing in the oven for a minimum of 4 minutes and until the applied mixture is dry.":
        "Поместите корпус сальника в печь на не менее 4 минут и до полного высыхания нанесённой смеси.",

    "Alternative procedure for paragraphs (g) to (j): apply Alocrom to the contact surface of the gland housing: refer to PCS-2220, type 2.":
        "Альтернативная процедура для пунктов (g) — (j): нанесите Alocrom на контактную поверхность корпуса сальника: обратитесь к PCS-2220, тип 2.",

    "Assemble the repair liner to the gland housing and hold it tightly with the masking tape, Material Ref. Item 08-715. Bond the masking tape, Material Ref. Item 08-715, to the adjacent adhesive PVC tape, Material Ref. Item TBA. Use one layer of the masking tape, Material Ref. Item 08-715, only at each side of the repair liner: make sure that the ends touch but do not overlap.":
        "Установите ремонтный вкладыш на корпус сальника и плотно закрепите его маскирующей лентой, мат. ссылка позиция 08-715. Приклейте маскирующую ленту, мат. ссылка позиция 08-715, к прилегающей клейкой ПВХ-ленте, мат. ссылка позиция TBA. Используйте один слой маскирующей ленты, мат. ссылка позиция 08-715, только с каждой стороны ремонтного вкладыша: убедитесь, что концы соприкасаются, но не перекрываются.",

    "Use a clamp to attach the repair liner to the gland housing.":
        "Используйте зажим для крепления ремонтного вкладыша к корпусу сальника.",

    "Put the gland housing in the oven, kept at between 35 and 45 oC (95 and 113 oF), for 345 to 375 minutes.":
        "Поместите корпус сальника в печь, поддерживаемую при температуре от 35 до 45 °C (от 95 до 113 °F), на 345–375 минут.",

    "Remove the gland housing from the oven and let its temperature decrease for a minimum of 30 minutes.":
        "Извлеките корпус сальника из печи и дайте ему остыть в течение не менее 30 минут.",

    # ── Repair 2-1 Pin (chromium plate diameters A and B) ─────────────────
    "Machine the diameters A and B to remove damage or wear after removal of the chromium plate. Remove the minimum amount of material necessary, to the dimensions shown in Figure 601, to remove the damage or wear.":
        "Обработайте диаметры A и B для удаления повреждения или износа после снятия хромового покрытия. Удалите минимально необходимое количество материала до размеров, указанных на Рисунке 601, для устранения повреждения или износа.",

    "Shot peen the machined areas: refer to M-DLPS123.":
        "Выполните дробеструйную обработку механически обработанных областей: обратитесь к M-DLPS123.",

    "Apply chromium plate to the diameters A and B: refer to M-DLPS101-2. Make sure the chromium plate terminations are smooth: refer to M-DLPS1031.":
        "Нанесите хромовое покрытие на диаметры A и B: обратитесь к M-DLPS101-2. Убедитесь, что окончания хромового покрытия гладкие: обратитесь к M-DLPS1031.",

    # ── Drawing annotations (Pin figure) ──────────────────────────────────
    "(0.039 to 0.078in) RADIUS":
        "(0.039 to 0.078in) РАДИУС",
    "(1.8090 to 1.8100in) AFTER GRINDING":
        "(1.8090 to 1.8100in) ПОСЛЕ ШЛИФОВАНИЯ",
    "CHROMIUM\t DEPOSIT":
        "ХРОМ\t НАНЕСЕНИЕ",
    "(0.078 to 0.118in) RADIUS":
        "(0.078 to 0.118in) РАДИУС",
    "(1.2186 to 1.2195in) AFTER GRINDING":
        "(1.2186 to 1.2195in) ПОСЛЕ ШЛИФОВАНИЯ",

    # ── Repair 3-1 Pivot Pin ──────────────────────────────────────────────
    "Examine the pivot pin for flaws: refer to PCS-3600 and PCS-3100, inclusion class 3.":
        "Проверьте штифт вращения на наличие дефектов: обратитесь к PCS-3600 и PCS-3100, класс включений 3.",

    "Apply chromium plate to the diameter A: refer to PCS-2110 Type B. Refer to Figure 601 for chromium plate termination information.":
        "Нанесите хромовое покрытие на диаметр A: обратитесь к PCS-2110 тип B. Обратитесь к Рисунку 601 для получения информации об окончании хромового покрытия.",

    "Grind the diameter A to between 15,960 and 15,987 mm (0.6284 and 0.6294 in). The surface finish must be 0,8 micrometers (32 micro-inches).":
        "Шлифуйте диаметр A до значения от 15,960 до 15,987 мм (0.6284 и 0.6294 дюйма). Шероховатость поверхности должна быть 0,8 микрометров (32 микродюймов).",

    "Examine the pivot pin for flaws: refer to PCS-3002, PCS-3100, inclusion class 3 and PCS-3600.":
        "Проверьте штифт вращения на наличие дефектов: обратитесь к PCS-3002, PCS-3100, класс включений 3 и PCS-3600.",

    "If the parent metal is damaged or worn:":
        "Если основной металл повреждён или изношен:",

    "Machine the diameter A sufficiently to remove damage and wear, down to a minimum of 15,377 mm (0.6054 in).":
        "Обработайте диаметр A в достаточной степени для удаления повреждения и износа, до минимального значения 15,377 мм (0.6054 дюйма).",

    # ── Drawing annotations (Pivot Pin figure) ────────────────────────────
    "RAD.":
        "РАД.",
    "RAD. MIN.":
        "РАД. МИН.",
    "IN THIS LENGTH. AN IRREGULAR LINE IS PERMITTED.":
        "В ЭТОЙ ДЛИНЕ. ДОПУСКАЕТСЯ НЕРОВНАЯ ЛИНИЯ.",

    # ── Repair 4-1 Uplock Pin ─────────────────────────────────────────────
    "Machine diameter A to remove the damage or wear after removal of the chromium plate. The minimum diameter is 24,36 mm (0.960 in) and the surface finish must be 0,4 micrometers (16 micro-inches).":
        "Обработайте диаметр A для удаления повреждения или износа после снятия хромового покрытия. Минимальный диаметр — 24,36 мм (0.960 дюйма), шероховатость поверхности должна быть 0,4 микрометров (16 микродюймов).",

    "If diameter A has been machined (see para (2)), shot peen the machined area: refer to M-DLPS123.":
        "Если диаметр A был механически обработан (см. п. (2)), выполните дробеструйную обработку обработанной области: обратитесь к M-DLPS123.",

    "Apply chromium plate to diameter A as shown with a minimum chromium plate thickness of 0,075 mm (0.0030 in): refer to M-DLPS101-2.":
        "Нанесите хромовое покрытие на диаметр A, как показано, с минимальной толщиной хромового покрытия 0,075 мм (0.0030 дюйма): обратитесь к M-DLPS101-2.",

    "Machine diameter A to between 24,947 and 24,980 mm (0.9822 and 0.9834 in) with a surface finish of 0,4 micrometers (16 micro-inches).":
        "Обработайте диаметр A до значения от 24,947 до 24,980 мм (0.9822 и 0.9834 дюйма) с шероховатостью поверхности 0,4 микрометров (16 микродюймов).",

    "Apply cadmium plate to the machined areas but not where chromium plated: refer to PCS-2141.":
        "Нанесите кадмиевое покрытие на механически обработанные области, кроме областей с хромовым покрытием: обратитесь к PCS-2141.",

    "450237490A if only the chromium plate has been repaired, or":
        "450237490A если отремонтировано только хромовое покрытие, или",

    "450237490B if chromium plate and parent metal have been repaired.":
        "450237490B если отремонтированы хромовое покрытие и основной металл.",

    # ── Drawing annotations (Uplock Pin figure) ───────────────────────────
    "(0.276 to 0.314in) RADIUS":
        "(0.276 to 0.314in) РАДИУС",
    "(0.384 to 0.403in) CENTERS TYPICAL":
        "(0.384 to 0.403in) ЦЕНТРЫ ТИПИЧНО",
    "(2.195 to 2.214in) LENGTH OF CHROMIUM PLATE":
        "(2.195 to 2.214in) ДЛИНА ХРОМОВОГО ПОКРЫТИЯ",
    "CHROMIUM PLATE\tM-DLPS1031-2 CHROMIUM PLATE TERMINATION CHROMIUM PLATE MUST NOT EXTENDED ONTO":
        "ХРОМОВОЕ ПОКРЫТИЕ\tM-DLPS1031-2 ОКОНЧАНИЕ ХРОМОВОГО ПОКРЫТИЯ ХРОМОВОЕ ПОКРЫТИЕ НЕ ДОЛЖНО ЗАХОДИТЬ НА",
    "7,00 to 8,00mm (0.276 to 0.314in) RADIUS":
        "7,00 to 8,00mm (0.276 to 0.314in) РАДИУС",

    # ── Repair 5-1 Pin (3-50) ─────────────────────────────────────────────
    "Apply chromium plate to diameter A to give a minimum diameter of 20,120 mm (0.7921 in): refer to M-DLPS101-2P.":
        "Нанесите хромовое покрытие на диаметр A до получения минимального диаметра 20,120 мм (0.7921 дюйма): обратитесь к M-DLPS101-2P.",

    # ── Drawing annotations (Pin 3-50 figure) ─────────────────────────────
    "MACHINE TO 19,380mm (0.763in) MIN. CHROMIUM PLATE TO 20,120mm (0.7921in)":
        "ОБРАБОТАТЬ ДО 19,380mm (0.763in) МИН. ХРОМОВОЕ ПОКРЫТИЕ ДО 20,120mm (0.7921in)",
    "GRIND TO 19,967 to 19,980mm (0.7861 to 0.7866mm)":
        "ШЛИФОВАТЬ ДО 19,967 to 19,980mm (0.7861 to 0.7866mm)",
    "(0.0236 to 0.0315in) RADIUS\t15 DEGREES":
        "(0.0236 to 0.0315in) РАДИУС\t15 ГРАДУСОВ",
    "(0.0315 to 0.0472in) RADIUS":
        "(0.0315 to 0.0472in) РАДИУС",

    # ── Repair 6-1 Pin (10-80) — bare metal conditions ────────────────────
    "If the bare metal is not damaged or corroded:":
        "Если основной металл не повреждён и не корродирован:",

    "Apply chromium plate to diameter A: refer to PCS-2110, Type C. Refer to Figure 601 for chromium plate termination information.":
        "Нанесите хромовое покрытие на диаметр A: обратитесь к PCS-2110, тип C. Обратитесь к Рисунку 601 для получения информации об окончании хромового покрытия.",

    "Grind diameter A to between 59,951 and 59,970 mm (2.3603 and 2.3610 in). The surface finish must be 0,8 micrometers (32 micro-inches).":
        "Шлифуйте диаметр A до значения от 59,951 до 59,970 мм (2.3603 и 2.3610 дюйма). Шероховатость поверхности должна быть 0,8 микрометров (32 микродюймов).",

    "If the bare metal is damaged or corroded:":
        "Если основной металл повреждён или корродирован:",

    "Machine diameter A just sufficiently to remove the damage or corrosion: refer to M-DLPS1004-4-1. The diameter must not be less than 59,370 mm":
        "Обработайте диаметр A в минимально достаточной степени для удаления повреждения или коррозии: обратитесь к M-DLPS1004-4-1. Диаметр должен быть не менее 59,370 мм",

    "(2.3374 in). The surface finish must be 1,6 micrometers (63 micro-inches).":
        "(2.3374 дюйма). Шероховатость поверхности должна быть 1,6 микрометров (63 микродюймов).",

    "Shot peen and apply chromium plate to diameter A: refer to M-DLPS123 and PCS-2110, Type C. Refer to Figure 601 for chromium plate termination information.":
        "Выполните дробеструйную обработку и нанесите хромовое покрытие на диаметр A: обратитесь к M-DLPS123 и PCS-2110, тип C. Обратитесь к Рисунку 601 для получения информации об окончании хромового покрытия.",

    # ── Repair 6-2 Pin (10-80) — repair bushes ────────────────────────────
    "Machine diameter A sufficiently to remove the damage or wear and to between 15,90 and 16,50 mm (0.626 and 0.649 in): refer to M-DLPS1004-4-1. Machine a surface finish of 1,6 micrometers (63 micro-inches).":
        "Обработайте диаметр A в достаточной степени для удаления повреждения или износа до значения от 15,90 до 16,50 мм (0.626 и 0.649 дюйма): обратитесь к M-DLPS1004-4-1. Обработайте с шероховатостью поверхности 1,6 микрометров (63 микродюймов).",

    "Calculate diameter C of the repair bushes:":
        "Рассчитайте диаметр C ремонтных втулок:",

    "C = A (as measured) + 0,010 to 0,039 mm (0.0004 to 0.0015 in).":
        "C = A (измеренный) + 0,010 до 0,039 мм (0.0004 до 0.0015 дюйма).",

    "Examine the repair bushes for flaws: refer to PCS-3100, inclusion class 3.":
        "Проверьте ремонтные втулки на наличие дефектов: обратитесь к PCS-3100, класс включений 3.",

    "Apply cadmium plate to all surfaces of the repair bushes: refer to M-DLPS100-1.":
        "Нанесите кадмиевое покрытие на все поверхности ремонтных втулок: обратитесь к M-DLPS100-1.",

    "Apply adhesive, Material Ref. Item 08-665, to the outside diameter of the repair bushes: refer to M-DLPS709-6.":
        "Нанесите клей, мат. ссылка позиция 08-665, на наружный диаметр ремонтных втулок: обратитесь к M-DLPS709-6.",

    "Install the repair bushes to diameter A until aligned with the outside diameter of the pin: refer to M-DLPS1011-5.":
        "Установите ремонтные втулки на диаметр A до совмещения с наружным диаметром штифта: обратитесь к M-DLPS1011-5.",

    # ── Drawing annotations (Repair 6-2 figure) ──────────────────────────
    "(0.50 to 0.51in) DIAMETER":
        "(0.50 to 0.51in) ДИАМЕТР",
    "X\tREPAIR BUSH 450258261":
        "X\tРЕМОНТНАЯ ВТУЛКА 450258261",
    "(0.56250 to 0.56379in) DIAMETER":
        "(0.56250 to 0.56379in) ДИАМЕТР",
    "14.5 to 15.5 DEGREES":
        "14.5 to 15.5 ГРАДУСОВ",

    # ── Repair 6-3 Pin (10-80) — sulphamate nickel plate ─────────────────
    "Machine the radii to the dimensions as shown: refer to Figure 601.":
        "Обработайте радиусы до размеров, указанных на Рисунке 601.",

    "Examine the part for flaws: refer to PCS-3100 inclusion class 4 and PCS-3600.":
        "Проверьте деталь на наличие дефектов: обратитесь к PCS-3100, класс включений 4 и PCS-3600.",

    "Shot peen the reworked areas over lapping adjacent angled surface by at least 6,35 mm (0.250 in). Almen A intensity to be 0,20 to 0,030 mm (0.008 to 0.012 in): refer to M-DLPS123.":
        "Выполните дробеструйную обработку переработанных областей с перекрытием прилегающей наклонной поверхности не менее чем на 6,35 мм (0.250 дюйма). Интенсивность Almen A должна быть от 0,20 до 0,030 мм (0.008 до 0.012 дюйма): обратитесь к M-DLPS123.",

    "Grit blast the reworked areas: refer to PCS-2610.":
        "Выполните пескоструйную обработку переработанных областей: обратитесь к PCS-2610.",

    "Machine (do not grind) the sulphamate nickel plate to get the bore diameter of 32,468 to 32,500 mm (1.2783 to 1.2795 in): refer to Figure 601. Make the surface finish 1,6":
        "Обработайте (не шлифуйте) сульфаматное никелевое покрытие для получения диаметра отверстия от 32,468 до 32,500 мм (1.2783 до 1.2795 дюйма): обратитесь к Рисунку 601. Обеспечьте шероховатость поверхности 1,6",

    "Machine the 20,000 mm (0.7874 in) radii as shown: refer to Figure 601.":
        "Обработайте радиусы 20,000 мм (0.7874 дюйма) как показано: обратитесь к Рисунку 601.",

    "If the pin base metal has been machined, examine the machined areas for flaws: refer to PCS-3600.":
        "Если основной металл штифта был механически обработан, проверьте обработанные области на наличие дефектов: обратитесь к PCS-3600.",

    "Grit blast the sulphamate nickel area: refer to PCS-2610. Make sure that the remainder of the pin is sufficiently masked.":
        "Выполните пескоструйную обработку области сульфаматного никеля: обратитесь к PCS-2610. Убедитесь, что остальная часть штифта достаточно замаскирована.",

    "If there is evidence of delamination, remove the sulphamate nickel plate and do the repair again.":
        "При наличии признаков расслоения удалите сульфаматное никелевое покрытие и выполните ремонт заново.",

    # ── Repair 7-2 Pin (11-130) — repair sleeves ─────────────────────────
    "Machine diameter A just sufficiently to remove the damage or corrosion and to between 14,25 and 14,75 mm (0.561 and 0.581 in): refer to M-DLPS1004-4-1. The surface finish must be 1,6 micrometers (63 micro-inches).":
        "Обработайте диаметр A в минимально достаточной степени для удаления повреждения или коррозии до значения от 14,25 до 14,75 мм (0.561 и 0.581 дюйма): обратитесь к M-DLPS1004-4-1. Шероховатость поверхности должна быть 1,6 микрометров (63 микродюймов).",

    "Calculate diameter B of the repair sleeves:":
        "Рассчитайте диаметр B ремонтных рукавов:",

    "Dia. B = Dia. A (as measured) + 0,010 to 0,039 mm (0.0004 to 0.0015 in).":
        "Диам. B = Диам. A (измеренный) + 0,010 до 0,039 мм (0.0004 до 0.0015 дюйма).",

    "Refer to Figure 601 and machine the repair sleeves to the dimensions shown and calculated.":
        "Обратитесь к Рисунку 601 и обработайте ремонтные рукава до указанных и рассчитанных размеров.",

    "Apply cadmium plate to the outside diameter and the chamfer of the repair sleeves: refer to PCS-2101.":
        "Нанесите кадмиевое покрытие на наружный диаметр и фаску ремонтных рукавов: обратитесь к PCS-2101.",

    "Apply adhesive, Material Ref. Item 08-665, to the outside diameter of the repair sleeves: refer to PCS-5303.":
        "Нанесите клей, мат. ссылка позиция 08-665, на наружный диаметр ремонтных рукавов: обратитесь к PCS-5303.",

    "Install the repair sleeves to diameters A until aligned with the outside diameter of the pin: refer to M-DLPS1011-5.":
        "Установите ремонтные рукава на диаметры A до совмещения с наружным диаметром штифта: обратитесь к M-DLPS1011-5.",

    # ── Drawing annotations (Repair 7-2 figure) ──────────────────────────
    "15 DEGREES":
        "15 ГРАДУСОВ",
    "(0.5000 to 0.5013in) DIAMETER":
        "(0.5000 to 0.5013in) ДИАМЕТР",

    # ── Repair 8-1 Bracket (5-300) — oversize bearing ─────────────────────
    "Machine the diameter A to remove the minimum amount of material necessary to remove the damage or wear: refer to Figure 601 for the dimensions. The surface finish must be 1,6 micrometers (63 micro-inches).":
        "Обработайте диаметр A, удалив минимально необходимое количество материала для устранения повреждения или износа: обратитесь к Рисунку 601 для получения размеров. Шероховатость поверхности должна быть 1,6 микрометров (63 микродюймов).",

    "Machine the face Q as necessary to remove damage or wear: refer to Figure 601 for the dimensions. The surface finish must be 1,6 micrometers (63 micro-inches).":
        "Обработайте поверхность Q при необходимости для удаления повреждения или износа: обратитесь к Рисунку 601 для получения размеров. Шероховатость поверхности должна быть 1,6 микрометров (63 микродюймов).",

    "Machine the chamfer to the dimensions shown in Figure 601.":
        "Обработайте фаску до размеров, указанных на Рисунке 601.",

    "Examine the bracket for flaws: refer to PCS-3200.":
        "Проверьте кронштейн на наличие дефектов: обратитесь к PCS-3200.",

    "Prepare the machined surfaces of the bracket:":
        "Подготовьте механически обработанные поверхности кронштейна:",

    "anodize the surfaces: refer to M-DLPS102-1, or":
        "анодируйте поверхности: обратитесь к M-DLPS102-1, или",

    "apply Alocrom to the surfaces: refer to PCS-2220.":
        "нанесите Alocrom на поверхности: обратитесь к PCS-2220.",

    "Calculate the diameter B and the dimension C of the oversize bearing:":
        "Рассчитайте диаметр B и размер C ремонтного подшипника увеличенного размера:",

    "B = A (as measured) - 0,006 to + 0,023 mm (- 0.0002 to + 0.0009 in)":
        "B = A (измеренный) - 0,006 до + 0,023 мм (- 0.0002 до + 0.0009 дюйма)",

    "C = D (as measured) - 0,15 to - 0,25 mm (- 0.006 to - 0.010 in).":
        "C = D (измеренный) - 0,15 до - 0,25 мм (- 0.006 до - 0.010 дюйма).",

    "Machine the oversize bearing to the dimensions shown and calculated: the surface finish must be 1,6 micrometers (63 micro-inches).":
        "Обработайте ремонтный подшипник увеличенного размера до указанных и рассчитанных размеров: шероховатость поверхности должна быть 1,6 микрометров (63 микродюймов).",

    "Passivate the oversize bearing: refer to M-DLPS124.":
        "Пассивируйте ремонтный подшипник увеличенного размера: обратитесь к M-DLPS124.",

    "Apply cadmium plate to the oversize bearing, but not on the internal diameter. The thickness of the cadmium plate must be between 0,010 and 0,015 mm (0.0004 and 0.0006 in): refer to M-DLPS100-2S.":
        "Нанесите кадмиевое покрытие на ремонтный подшипник увеличенного размера, кроме внутреннего диаметра. Толщина кадмиевого покрытия должна быть от 0,010 до 0,015 мм (0.0004 и 0.0006 дюйма): обратитесь к M-DLPS100-2S.",

    "Apply sealant, Material Ref. Item 09-510A, to seal between the ends of the oversize bearing and the bracket: refer to M-DLPS709-19.":
        "Нанесите герметик, мат. ссылка позиция 09-510A, для уплотнения между торцами ремонтного подшипника увеличенного размера и кронштейном: обратитесь к M-DLPS709-19.",

    # ── Repair 8-2 Bracket (5-300) — oversize bearing (variant) ───────────
    "Machine the diameter A sufficiently to remove the damage or wear: refer to Figure 601 for the dimensions. The surface finish must be 1,6 micrometers (63 micro-inches).":
        "Обработайте диаметр A в достаточной степени для удаления повреждения или износа: обратитесь к Рисунку 601 для получения размеров. Шероховатость поверхности должна быть 1,6 микрометров (63 микродюймов).",

    "Machine the face Q as necessary to remove the damage or wear: refer to Figure 601 for the dimensions. The surface finish must be 1,6 micrometers (63 micro-inches).":
        "Обработайте поверхность Q при необходимости для удаления повреждения или износа: обратитесь к Рисунку 601 для получения размеров. Шероховатость поверхности должна быть 1,6 микрометров (63 микродюймов).",

    "C = D (as measured) - 0,30 to - 0,40 mm (- 0.011 to - 0.015 in).":
        "C = D (измеренный) - 0,30 до - 0,40 мм (- 0.011 до - 0.015 дюйма).",

    # ── Shared paragraphs appearing in multiple repairs ───────────────────
    "Shot peen diameter A: refer to M-DLPS123.":
        "Выполните дробеструйную обработку диаметра A: обратитесь к M-DLPS123.",

    "Shot peen the pin: refer to M-DLPS123.":
        "Выполните дробеструйную обработку штифта: обратитесь к M-DLPS123.",

    "Apply cadmium plate all over the pin, but not on the chromium plated areas: refer to M-DLPS100-2 or PCS-2141.":
        "Нанесите кадмиевое покрытие по всей поверхности штифта, кроме областей с хромовым покрытием: обратитесь к M-DLPS100-2 или PCS-2141.",

    # ── Drawing dimension annotations with English words ──────────────────
    "45,300mm (1.7834in)  DIAMETER MINIMUM":
        "45,300mm (1.7834in)  МИНИМАЛЬНЫЙ ДИАМЕТР",
    "30,300mm (1.1929in)   DIAMETER MINIMUM":
        "30,300mm (1.1929in)   МИНИМАЛЬНЫЙ ДИАМЕТР",
    "1,00mm (0.039in) MAXIMUM":
        "1,00mm (0.039in) МАКСИМУМ",
    "2,00mm (0.078in) MAXIMUM":
        "2,00mm (0.078in) МАКСИМУМ",
    "(0.078in) MAXIMUM":
        "(0.078in) МАКСИМУМ",
    "DIA. B REPAIR SLEEVE 450258431":
        "ДИАМ. B РЕМОНТНЫЙ РУКАВ 450258431",
    "DIAMETER MINIMUM":
        "МИНИМАЛЬНЫЙ ДИАМЕТР",
    "2,00mm (0.079in) MAX. CHROMIUM PLATE MUST STOP":
        "2,00mm (0.079in) МАКС. ХРОМОВОЕ ПОКРЫТИЕ ДОЛЖНО ЗАКАНЧИВАТЬСЯ",
    "2,00mm (0.079in) MIN. LENGTH":
        "2,00mm (0.079in) МИН. ДЛИНА",
    "10,00mm (0.394in) DIAMETER":
        "10,00mm (0.394in) ДИАМЕТР",
}
